colour-science/colour

- colour/colorimetry/__init__.py
- colour/colorimetry/photometry.py
- colour/colorimetry/tests/tests_photometry.py
> PR: Implement "Luminous Efficacy" computation.

- colour/volume/__init__.py
- colour/volume/mesh.py
- colour/volume/pointer_gamut.py
- colour/volume/rgb.py
- colour/volume/spectrum.py
- colour/volume/tests/tests_mesh.py
- colour/volume/tests/tests_rgb.py
- colour/volume/tests/tests_spectrum.py
> PR: Implement support for "Visible Spectrum" coverage computation.

- colour/models/__init__.py
- colour/models/cie_lab.py
- colour/models/cie_luv.py
- colour/models/cie_uvw.py
- colour/models/cie_xyy.py
- colour/models/rgb.py
- colour/models/tests/tests_cie_lab.py
- colour/models/tests/tests_cie_luv.py
- colour/models/tests/tests_cie_uvw.py
- colour/models/tests/tests_cie_xyy.py
- colour/models/tests/tests_rgb.py
> PR: Implement support for illuminant arguments with Luminance value in various "colour.models" definitions.

- colour/colorimetry/__init__.py
- colour/colorimetry/spectrum.py
- colour/colorimetry/tests/tests_spectrum.py
- colour/io/tests/tests_ies_tm2714.py
- colour/utilities/__init__.py
- colour/utilities/array.py
- colour/utilities/data_structures.py
- colour/utilities/tests/tests_data_structures.py
> PR: Fix inconsistencies in support for fractional steps size in "colour.SpectralPowerDistribution" class.

- colour/__init__.py
> PR: Add "Python 2.6" deprecation messages to "Colour 0.3.6".

- colour/colorimetry/spectrum.py
- colour/colorimetry/tests/tests_spectrum.py
- colour/examples/colorimetry/examples_spectrum.py
This PR ensures that regular arithmetical operations don't happen in-place and also implement proper support for in-place arithmetical operations in `colour.SpectralPowerDistribution` and `colour.TriSpectralPowerDistribution` classes.
References #217.
> PR: Implement support for better arithmetical operations behaviour.

- colour/difference/delta_e.py
- colour/difference/tests/tests_delta_e.py
> PR: Amend parametric factors usage in "CIE 1994"  & "CIE 2000" colour differences definitions.

- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/canon_log.py
- colour/models/rgb/transfer_functions/tests/tests_canon_log.py
> PR: Implement support for "Canon Log 2" and "Canon Log 3" log encoding curves.

- colour/appearance/tests/tests_llab.py
> PR: Correctly subclass generator methods in the LLAB tests.

- colour/models/rgb/__init__.py
- colour/models/rgb/dataset/aces.py
- colour/models/rgb/dataset/adobe_rgb_1998.py
- colour/models/rgb/dataset/alexa_wide_gamut_rgb.py
- colour/models/rgb/dataset/cie_rgb.py
- colour/models/rgb/dataset/cinema_gamut.py
- colour/models/rgb/dataset/dci_p3.py
- colour/models/rgb/dataset/rimm_romm_rgb.py
- colour/models/rgb/dataset/v_gamut.py
- colour/models/rgb/rgb_colourspace.py
- colour/models/rgb/tests/tests_rgb_colourspace.py
> PR: Implement support for initialisation time and derived transformation matrices in "colour.RGB_Colourspace" class.

- colour/difference/__init__.py
- colour/difference/delta_e_luo2006.py
- colour/difference/tests/tests_delta_e_luo2006.py
- colour/models/__init__.py
- colour/models/tests/tests_ucs_luo2006.py
- colour/models/ucs_luo2006.py
> PR: Implement support for "Luo et al (2006)" UCS colourspaces.

- colour/models/rgb/transfer_functions/gamma.py
- colour/models/rgb/transfer_functions/tests/tests_gamma.py
> PR: Implement support for negative number handling in "colour.gamma" definition.

- colour/models/rgb/transfer_functions/bt_1886.py
- colour/models/rgb/transfer_functions/tests/tests_bt_1886.py
> Change "colour.eotf_BT1886" and "colour.oetf_BT1886" definitions default arguments.

- .travis.yml
> Specify exact "Scipy" version for unit tests.

- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/arib_std_b67.py
- colour/models/rgb/transfer_functions/tests/tests_arib_std_b67.py
> Implement support for "ARIB STD-B67" OETF.

- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/dicom_gsdf.py
- colour/models/rgb/transfer_functions/tests/tests_dicom_gsdf.py
> Implement support for "DICOM - Grayscale Standard Display Function".

- colour/examples/models/examples_prismatic.py
- colour/models/rgb/__init__.py
- colour/models/rgb/prismatic.py
- colour/models/rgb/tests/tests_prismatic.py
> Implement support for "Prismatic" colourspace.

- colour/colorimetry/__init__.py
- colour/colorimetry/tests/tests_yellowness.py
- colour/colorimetry/yellowness.py
- colour/examples/colorimetry/examples_yellowness.py
> Implement "Yellowness" computation support.

- colour/__init__.py
- colour/biochemistry/__init__.py
- colour/biochemistry/michaelis_menten.py
- colour/biochemistry/tests/__init__.py
- colour/biochemistry/tests/tests_michaelis_menten.py
- colour/colorimetry/__init__.py
- colour/colorimetry/lightness.py
- colour/colorimetry/luminance.py
- colour/colorimetry/tests/tests_lightness.py
- colour/colorimetry/tests/tests_luminance.py
- colour/examples/colorimetry/examples_lightness.py
- colour/examples/colorimetry/examples_luminance.py
- colour/examples/models/examples_models.py
- colour/models/__init__.py
- colour/models/hdr_cie_lab.py
- colour/models/hdr_ipt.py
- colour/models/tests/tests_hdr_cie_lab.py
- colour/models/tests/tests_hdr_ipt.py
> Implement support for "hdr-CIELab" and "hdr-IPT" colourspaces.

- colour/appearance/ciecam02.py
Check for and handle negative values as per the formulas on pp. 50-51 of
http://4843ec7c-89cf-4d26-a36a-0e40ebc9a3a7.s3.amazonaws.com/9781441961891-c1.pdf.
> Check for and handle negative values in post_adaptation_non_linear_response_compression_forward()

- colour/examples/recovery/examples_meng2015.py
- colour/recovery/__init__.py
- colour/recovery/meng2015.py
- colour/recovery/tests/tests_meng2015.py
> PR: Implement support for "Meng et al. (2015)" reflectance recovery.

- colour/appearance/ciecam02.py
- colour/appearance/tests/common.py
- colour/appearance/tests/tests_ciecam02.py
- colour/utilities/__init__.py
- colour/utilities/array.py
- colour/utilities/tests/tests_array.py
> PR: Update "colour.CIECAM02_to_XYZ" definition signature to use "colour.CIECAM02_Specification" class.

- colour/colorimetry/__init__.py
- colour/colorimetry/lightness.py
- colour/colorimetry/luminance.py
- colour/colorimetry/tests/test_lightness.py
- colour/colorimetry/tests/test_luminance.py
- colour/models/__init__.py
- colour/models/hdr_cie_lab.py
- colour/models/hdr_ipt.py
- colour/models/tests/test_hdr_cie_lab.py
- colour/models/tests/test_hdr_ipt.py
> PR: Implement support for "hdr-CIELab" and "hdr-IPT" (2011) colourspaces.

- colour/models/rgb/transfer_functions/canon_log.py
- colour/models/rgb/transfer_functions/panasonic_vlog.py
- colour/models/rgb/transfer_functions/tests/test_canon_log.py
- colour/models/rgb/transfer_functions/tests/test_panasonic_vlog.py
> PR: Improve "Canon Log" and "Panasonic V-Log" curves implementation and consistency.

- BIBLIOGRAPHY.bib
- colour/__init__.py
- colour/models/__init__.py
- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/arib_std_b67.py
- colour/models/rgb/transfer_functions/itur_bt_2100.py
- colour/models/rgb/transfer_functions/tests/test_arib_std_b67.py
- colour/models/rgb/transfer_functions/tests/test_itur_bt_2100.py
- docs/colour.models.rst
- docs/generated/colour.models.BT2100_HLG_EOTF_METHODS.rst
- docs/generated/colour.models.BT2100_HLG_EOTF_REVERSE_METHODS.rst
- docs/generated/colour.models.BT2100_HLG_OOTF_METHODS.rst
- docs/generated/colour.models.BT2100_HLG_OOTF_REVERSE_METHODS.rst
- docs/generated/colour.models.eotf_HLG_BT2100.rst
- docs/generated/colour.models.eotf_PQ_BT2100.rst
- docs/generated/colour.models.eotf_reverse_HLG_BT2100.rst
- docs/generated/colour.models.eotf_reverse_PQ_BT2100.rst
- docs/generated/colour.models.oetf_HLG_BT2100.rst
- docs/generated/colour.models.oetf_PQ_BT2100.rst
- docs/generated/colour.models.oetf_reverse_HLG_BT2100.rst
- docs/generated/colour.models.oetf_reverse_PQ_BT2100.rst
- docs/generated/colour.models.ootf_HLG_BT2100.rst
- docs/generated/colour.models.ootf_PQ_BT2100.rst
- docs/generated/colour.models.ootf_reverse_HLG_BT2100.rst
- docs/generated/colour.models.ootf_reverse_PQ_BT2100.rst
> PR: Implement support for "ITUR BT.2100-2".

- colour/characterisation/correction.py
> PR: Update docstrings in "correction.py" module.

- README.rst
- colour/colorimetry/__init__.py
- colour/colorimetry/tests/test_tristimulus.py
- colour/colorimetry/tristimulus.py
- colour/examples/colorimetry/examples_tristimulus.py
- colour/utilities/metrics.py
- colour/volume/spectrum.py
- docs/colour.colorimetry.rst
- docs/generated/colour.colorimetry.multi_sds_to_XYZ_ASTME308.rst
- docs/index.rst
Add "colour.colorimetry.multi_sds_to_XYZ_ASTME308" definition.
> PR: Implement support for "colour.MultiSpectralDistribution" class instances to "colour.multi_sds_to_XYZ" definition.

- colour/io/image.py
> PR: Implement support for "OpenImageIO" 2.x.

- colour/algebra/interpolation.py
- colour/continuous/multi_signals.py
- colour/continuous/signal.py
- colour/plotting/models.py
- colour/utilities/array.py
- colour/utilities/data_structures.py
Fixed from collections import Mapping, MutableMapping with Python 3.8 in reference to the issue #511
> Fixed from collections import Mapping, MutableMapping with Python 3.8

- colour/models/rgb/transfer_functions/__init__.py
> PR: Fix missing spaces in various docstrings.

- .github/workflows/continuous-integration.yml
- colour/continuous/tests/test_multi_signal.py
- colour/io/luts/lut.py
- colour/plotting/common.py
- colour/utilities/deprecation.py
This PR uses one of the commits from @MaxSchambach in #544 and fixes various other issues with Python 3.8 while enabling CI for it.
> PR: Implement support for Python 3.8.

- colour/__init__.py
- colour/colorimetry/__init__.py
- colour/colorimetry/generation.py
- colour/colorimetry/tests/test_generation.py
- docs/colour.colorimetry.rst
This PR adds the following definitions:
- `colour.msds_constant`
- `colour.msds_zeros`
- `colour.msds_ones`
> PR: MSDS Generators.

- colour/io/ies_tm2714.py
…_Specification_IESTM2714 ctor.
> PR: Attribute is listed twice in the docstring for IES TM-27-14's "Element_Specification_IESTM2714" class.

- README.rst
- colour/models/rgb/datasets/davinci_wide_gamut.py
- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/davinci_intermediate.py
- colour/models/rgb/transfer_functions/tests/test_davinci_intermediate.py
- docs/colour.models.rst
- docs/index.rst
Replaces #660 as @fredsavoir deleted the branch.
We might actually merge it "ad interim" now that the commits are squashed and do not affect the gamut primaries. Still requires various documentation updates, etc... before though.
> PR: Implement support for "DaVinci Intermediate" log encoding.

- colour/models/rgb/datasets/davinci_wide_gamut.py
This PR adds the *DaVinci Wide Gamut* conversion matrices as given in the white paper and in support to https://github.com/colour-science/colour/discussions/762.
> PR: Add "DaVinci Wide Gamut" conversion matrices as given in the white paper.

- colour/models/rgb/ictcp.py
- colour/models/rgb/tests/test_ictcp.py
References #764.
Let's try that again shall we?
> PR: Implement fixes for "ICtCp" colour encoding and "ITU-R BT.2100" support.

- README.rst
- colour/colorimetry/__init__.py
- colour/colorimetry/tests/test_yellowness.py
- colour/colorimetry/yellowness.py
- colour/examples/colorimetry/examples_yellowness.py
- docs/colour.colorimetry.rst
- docs/index.rst
References #779.
@romanovar for vis! :)
> PR: Implement support for current ASTME313 Yellowness Index computation.

- BIBLIOGRAPHY.bib
- colour/__init__.py
- colour/colorimetry/__init__.py
- colour/colorimetry/spectrum.py
- colour/colorimetry/tests/test_uniformity.py
- colour/colorimetry/uniformity.py
- colour/examples/colorimetry/examples_uniformity.py
- docs/colour.colorimetry.rst
This PR implements spectral uniformity computation according to *David et al. (2015)* method.
References #816.
> PR: Implement support for spectral uniformity computation.

- README.rst
- colour/biochemistry/__init__.py
- colour/biochemistry/michaelis_menten.py
- colour/biochemistry/tests/test_michaelis_menten.py
- colour/colorimetry/__init__.py
- colour/colorimetry/lightness.py
- colour/colorimetry/luminance.py
- colour/colorimetry/tests/test_lightness.py
- colour/colorimetry/tests/test_luminance.py
- docs/colour.biochemistry.rst
- docs/colour.colorimetry.rst
- docs/index.rst
> PR: Implement support for "Abebe et al. (2017)" lightness computation.

- colour/appearance/zcam.py
This PR fixes the following issues:
#908 
#909
> Fix: #908  #909

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/documentation-improvement.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- .github/ISSUE_TEMPLATE/question.yml
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds various new issue and pull request templates to help us triaging things a bit:
- Bug Report
- Feature Request
- Documentation Improvement
- Question
- PR
> PR: Add issue and pull request templates.

- BIBLIOGRAPHY.bib
- colour/difference/__init__.py
- colour/difference/delta_e.py
- colour/difference/tests/test_delta_e.py
- colour/examples/difference/examples_delta_e.py
- docs/colour.difference.rst
Implementing dEITP per ITU-R BT.2124-0 recommendation. 
> PR: Implement support for "Recommendation ITU-R BT.2124-0", i.e. DeltaE IPT.

- colour/recovery/tests/test_jakob2019.py
This PR integrates @tjdcs code in #1036 to optimise the *Jakob and Hanika (2019)* LUT unit tests speed.
> PR: Improve "Jakob and Hanika (2019)" LUT unit tests.

- colour/characterisation/tests/test_aces_it.py
- colour/colorimetry/dominant.py
- colour/colorimetry/tests/test_dominant.py
- colour/continuous/multi_signals.py
- colour/continuous/signal.py
- colour/continuous/tests/test_signal.py
- colour/io/tests/test_tm2714.py
- colour/plotting/temperature.py
- colour/recovery/jakob2019.py
- colour/recovery/tests/test_jakob2019.py
- colour/utilities/tests/test_deprecation.py
- colour/volume/macadam_limits.py
This PR improves the coverage.
> PR: Improve Coverage
