colour-science/colour

- colour/io/tabular.py
There is an artifact when files are processed as a ASCII that creates an extra line feed at the end of a line in windows.  If the file is written as a binary this is not an issue.
> PR: Prevent extra line breaks on "Windows" when exporting CSV files.

- colour/models/rgb/__init__.py
- colour/models/rgb/conversion_functions/__init__.py
- colour/models/rgb/conversion_functions/bt_1886.py
- colour/models/rgb/conversion_functions/log.py
- colour/models/rgb/conversion_functions/st_2084.py
- colour/models/rgb/conversion_functions/tests/__init__.py
- colour/models/rgb/conversion_functions/tests/tests_bt_1886.py
- colour/models/rgb/conversion_functions/tests/tests_log.py
- colour/models/rgb/conversion_functions/tests/tests_st_2084.py
References #244, #245.
Pending for discussion are still the various RGB colourspace *OECF* and *EOCF* naming convention.
https://docs.google.com/spreadsheets/d/1x_JZuSgZNEllzl6qxxbz7D-FJ47iF5ZKIIMSaRxPz0E/edit?usp=sharing
> PR: Implement support for "Recommendation ITU-R BT.1886" and "SMPTE ST 2084:2014".

- colour/models/rgb/__init__.py
- colour/models/rgb/tests/tests_ycbcr.py
- colour/models/rgb/ycbcr.py
First version of a set of functions for converting between RGB and Y'CbCr or Yc'Cbc'Cbr' (the 'constant luminance' variant for ITU-R BT.2020 – Rec.2020).
The functions are designed to be as flexible as possible, so they can take input and return values in various integer and floating point ranges, and can use various preset matrices (or user ones) to do the conversion.
The unit tests are not yet sufficiently comprehensive, but this is put out there for feedback before being taken any further.
> PR: Implement support for "Y'CbCr" colourspace.

- colour/examples/temperature/examples_cct.py
- colour/temperature/__init__.py
- colour/temperature/cct.py
- colour/temperature/tests/tests_cct.py
References #296.
As I just bought the Cloud version of the paper (and thus cannot save it), here are the relevant equations:
> PR: Implement support for CCT to chromaticity coordinates computation from "Krystek (1985)".

- colour/difference/delta_e_luo2006.py
It was erroneously specified as 2016 thereout.
> Correct Luo et al. (2006) publication year in docstrings

- colour/appearance/ciecam02.py
Ensure J cannot be below 1e-16 in temporary_magnitude_quantity_reverse().
> Fix divide by zero in ciecam02.py temporary_magnitude_quantity_reverse()

- colour/appearance/ciecam02.py
When t=0 in CIECAM02 reverse mode (i.e. the user has input pure black) there will be a division by zero when computing P_1. Since P_1 may not be a scalar, I disable the division warning for that line and manually test for finite elements of P_1. According to "CIECAM02 and Its Recent Developments" (http://4843ec7c-89cf-4d26-a36a-0e40ebc9a3a7.s3.amazonaws.com/9781441961891-c1.pdf) p. 53, if t=0, then a=b=0 and as such I only write to elements of a and b where P_1 is finite.
> Fix divide by zero warning in CIECAM02 reverse mode

- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/aces.py
- colour/models/rgb/transfer_functions/common.py
- colour/models/rgb/transfer_functions/sony_slog.py
- colour/models/rgb/transfer_functions/tests/tests_aces.py
- colour/models/rgb/transfer_functions/tests/tests_common.py
- colour/models/rgb/transfer_functions/tests/tests_sony_slog.py
- colour/models/rgb/ycbcr.py
> PR: Fix and improve "Sony S-Log" curves implementation errors and consistency.

- BIBLIOGRAPHY.bib
- README.rst
Hello :-)
The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). Accordingly, this PR updates all DOI links.
Cheers!
> Hyperlink DOIs against preferred resolver

- BIBLIOGRAPHY.bib
- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/filmic_pro.py
- colour/models/rgb/transfer_functions/tests/test_common.py
- colour/models/rgb/transfer_functions/tests/test_filmic_pro.py
References #433.
This is a very poor curve in its current state but given it seems to be used quite a lot on iOS (and I did use it today at work), better have it there! Their fit precision is poor and it is non-invertible. I'm using a *LUT* for inversion, should be precise enough at 7 digits.
> PR: Implement support for "Filmic Pro 6" log encoding curve.

- BIBLIOGRAPHY.bib
- colour/colorimetry/__init__.py
- colour/colorimetry/illuminants.py
- colour/colorimetry/tests/test_illuminants.py
- colour/temperature/cct.py
- docs/colour.colorimetry.rst
- docs/generated/colour.colorimetry.daylight_locus_function.rst
We are computing the *Daylight Locus* implicitly here: https://github.com/colour-science/colour/blob/cd891c2abed839d350423b02e30c9f78e01a8071/colour/temperature/cct.py#L983 but this PR exposes it as a proper function so that it can be specified from a chromaticity coordinate `x_D` as given in Wyszecki and Styles (2000).
> PR: Expose "Daylight Locus" function.

- README.rst
The Colorspacious Python library is good but it doesn't include more recent models than CAM02-UCS such as CAM-16, Jzazbz, ICtCp etc. Colorio supports these.
The Colorspacious author clearly states inability to update the library:
https://github.com/njsmith/colorspacious/issues/10
https://github.com/njsmith/colorspacious/issues/13
So definitely Colorio should be mentioned above Colorspacious as it is better than the letter.
> Add Colorio to "See Also" section of README

- colour/examples/temperature/examples_cct.py
- colour/notation/munsell.py
- colour/notation/tests/test_munsell.py
- colour/temperature/cct.py
- colour/temperature/tests/test_cct.py
- colour/utilities/__init__.py
- colour/utilities/common.py
- colour/utilities/tests/test_common.py
- colour/volume/rgb.py
- colour/volume/tests/test_rgb.py
- docs/basics.rst
- docs/colour.utilities.rst
- docs/generated/colour.utilities.disable_multiprocessing.rst
- docs/generated/colour.utilities.multiprocessing_pool.rst
The following definitions have received a bit of love, i.e. n-dimensional arrays support ~and multiprocessing~:
- `colour.notation.munsell_specification_to_xyY`
- `colour.notation.xyY_to_munsell_specification`
- `colour.munsell_colour_to_xyY`
- `colour.xyY_to_munsell_colour`
- `colour.cct.uv_to_CCT_Ohno2013`
- `colour.cct.CCT_to_uv_Ohno2013`
- `colour.cct.uv_to_CCT_Robertson1968`
- `colour.cct.CCT_to_uv_Robertson1968`
- `colour.CCT_to_uv`
- `colour.uv_to_CCT`
I added two new context manager: the `colour.utilities.multiprocessing_pool` context manager that provides a multiprocessing pool and the `colour.utilities.disable_multiprocessing` that disable multiprocessing if used.
> PR: Implement support for n-dimensional arrays and multiprocessing to various definitions.

- colour/models/__init__.py
Deprecated 'models.XYZ_to_colourspace_model' in reference to issue #508
> PR: Deprecate "colour.models.XYZ_to_colourspace_model" definition.

- LICENSE
- THIRD_PARTY
Just a recommendation - this makes the GitHub automatic license identifier properly tag this project as BSD-3-Clause versus Unknown ( which also helps the ASWF Landscape identify the license as well ).
> Move third party notices from LICENSE to THIRD_PARTY

- colour/appearance/tests/common.py
- colour/appearance/tests/test_llab.py
References #518 .
This is probably the minimum possible change that avoids the generator based tests.
Instead of yielding tests, each check is executed, resulting in a single test that checks the whole dataset for each CAM.
A fancier version could use [pytest's parametrized test fixtures](http://doc.pytest.org/en/latest/parametrize.html) to re-create the one test per case behaviour we had before. But I'm not sure we actually need that.
> PR: Replace generator based tests.

- colour/models/rgb/ycbcr.py
Fixes default values in `colour.models.rgb.ycbcr.YCbCr_to_RGB`s docstring maybe coming from copy-pasting the docstring from `colour.models.rgb.ycbcr.RGB_to_YCbCr`.
> Fix default values in docstring

- CODE_OF_CONDUCT.md
This is mostly because I noticed that GitHub showed the repo as not having a Code of Conduct on the "Insights/Community" site. That is also why it is reformatted as Markdown: from what I have seen, only markdown files are picked up by the system.
> PR: Add code of conduct from website to repository.

- colour/colorimetry/spectrum.py
Fix `TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer` reported with numpy 1.18.0rc1.
> PR: Fix "TypeError" exception caused by "Numpy" 1.18 in "colour.SpectralShape.range" method.

- BIBLIOGRAPHY.bib
- colour/__init__.py
- colour/characterisation/datasets/__init__.py
- colour/characterisation/datasets/filters/__init__.py
- colour/characterisation/datasets/filters/sds.py
- colour/characterisation/datasets/lenses/__init__.py
- colour/characterisation/datasets/lenses/sds.py
- colour/colorimetry/datasets/illuminants/chromaticity_coordinates.py
- colour/colorimetry/datasets/illuminants/sds.py
- colour/colorimetry/datasets/light_sources/sds.py
- docs/colour.characterisation.rst
This PR adds the spectral distributions of *ISO* 7589 illuminants and the related lens and diffuser:
The following new spectral distributions are available:
-   ISO 7589 Photographic Daylight
-   ISO 7589 Sensitometric Daylight
-   ISO 7589 Studio Tungsten
-   ISO 7589 Sensitometric Studio Tungsten
-   ISO 7589 Photoflood
-   ISO 7589 Sensitometric Photoflood
-   ISO 7589 Sensitometric Printer
Along with:
- ISO 6728 Standard Lens
- ISO 7589 Diffuser
Colour has also now the following new attributes:
- `colour.LENS_SDS` that contains *ISO 6728 Standard Lens*
- `colour.FILTER_SDS` that contains *ISO 7589 Diffuser*
> PR: Add "ISO" 7589 spectral distributions.

- colour/examples/plotting/examples_volume_plots.py
In original example, the argument 'style' is useless.
Correcting the arguments for the example.
> PR: Fix example of "colour.plotting.plot_RGB_colourspaces_gamuts" definition.

- README.rst
- colour/models/rgb/transfer_functions/__init__.py
- docs/index.rst
`'ITU-R BT.2100 HLG'` was incorrectly written as `'ITU-R BT.2100 HLD'` See also #571 .
> PR: Fix incorrect spelling of HLG inverse OETF

- colour/io/luts/cinespace_csp.py
- colour/io/luts/common.py
- colour/io/luts/iridas_cube.py
- colour/io/luts/resolve_cube.py
- colour/io/luts/sony_spi1d.py
- colour/io/luts/sony_spi3d.py
- colour/io/luts/tests/test_common.py
- colour/io/luts/tests/test_sony_spi3d.py
This change makes colour more optimized with respect to its LUT I/O capabilities, and also address the issue: #573.
> PR: Remove "colour.io.luts.common.parse_array" definition usage.

- colour/models/cie_luv.py
- colour/models/cie_ucs.py
- colour/models/rgb/cmyk.py
- colour/models/rgb/cylindrical.py
- colour/models/rgb/transfer_functions/aces.py
- colour/models/rgb/transfer_functions/itur_bt_2100.py
Hello, This is a pull request for small microoptimizations. 
The optimizations for the models/rgb are small and get about 5-10% speedup, while the optimizations for the transfer_functions module although small get about 40-50% for the last two and about 90% for the aces function.
As for comments on the previous pull request (sorry my local repository got deleted and so i had to close that one)
The X_Y_Z and X_r_Y_r_Z_r variables don't seem to have a more descriptive name as far as I've searched and the U_V_W would need to be tstacked to divide over the entire variable, losing some performance.
> PR: Micro-optimizations for the "colour.models" sub-package.

- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/log.py
- colour/models/rgb/transfer_functions/tests/test_log.py
- docs/colour.models.rst
This pull request adds the `log.py` module to the 'transfer functions' sub-package in colour models, and contains the following functions:
- `log_encoding_Log2`
- `log_decoding_Log2`
> PR: Add "colour.models.rgb.transfer_functions.log" module.

- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/exponent.py
- colour/models/rgb/transfer_functions/tests/test_exponent.py
- docs/colour.models.rst
This pull request adds the `exponent.py` module to the 'transfer functions' sub-package in colour models, and contains the following functions:
* `exponent_function_basic`
* `exponent_function_monitor_curve`
> PR: Add "colour.models.rgb.transfer_functions.exponent" module.

- colour/temperature/mccamy1992.py
I believe the comment should say "*not* a bijective function", in order to match the usage warning later in the same file.
> PR: Fix "CCT_to_xy_McCamy1992" comment typo.

- colour/__init__.py
- colour/models/rgb/__init__.py
- colour/models/rgb/tests/test_ycbcr.py
- colour/models/rgb/ycbcr.py
- docs/colour.models.rst
> PR: Implement support for Y'CbCr matrices generation.

- colour/algebra/__init__.py
- colour/algebra/geometry.py
- colour/algebra/tests/test_geometry.py
- docs/colour.algebra.rst
This PR implements support for the *Manhattan* distance computation, i.e. `|xa - xb| + |ya - yb|`.
Given the simplicity and as it follows the same structure than `colour.algebra.euclidean_distance`, I will merge directly when tests pass.
> PR: Implement support for "Manhattan" distance computation.

- colour/models/rgb/ictcp.py
- colour/models/rgb/tests/test_ictcp.py
This PR implements the *ICtCp* matrix as given in *ITU-R BT.2100-2* for *HLG*.
**ITU-R BT.2100-1**
**ITU-R BT.2100-2**
Thanks @Valzapod for the heads-up!
> PR: Implement support for "ICtCp" matrix as given in "ITU-R BT.2100-2" for "HLG".

- colour/__init__.py
- colour/difference/__init__.py
- colour/difference/huang2015.py
- colour/difference/stress.py
- colour/difference/tests/test_huang2015.py
- colour/difference/tests/test_stress.py
- docs/colour.difference.rst
Long time coming! This PR implements support for *Huang et al. (2015)* Power-Functions. They basically improve the colour difference formulas by applying a simple power-function on the computed delta_E value:
- `colour.difference.power_function_Huang2015`
I also took that opportunity to implement the STRESS index as given by García et al. (2007):
- `colour.index_stress`, maybe we should call it `stress_index` but it is consistent right now.
- `colour.INDEX_STRESS_METHODS`
- `colour.difference.index_stress_Garcia2017`
> PR: Implement support for "Huang et al. (2015)" Power-Functions.

- colour/colorimetry/tests/test_uniformity.py
- colour/colorimetry/uniformity.py
> PR: Implement support for second-order derivatives in "colour.spectral_uniformity" definition.

- colour/graph/conversion.py
- colour/models/cam02_ucs.py
- colour/models/cam16_ucs.py
- colour/utilities/array.py
There are small typos in:
- colour/graph/conversion.py
- colour/models/cam02_ucs.py
- colour/models/cam16_ucs.py
- colour/utilities/array.py
Fixes:
- Should read `ambient` rather than `ambiant`.
- Should read `indices` rather than `indixes`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> PR: docs: Fix a few typos

- colour/examples/recovery/examples_otsu2018.py
- colour/recovery/__init__.py
- colour/recovery/otsu2018.py
- colour/recovery/tests/test_otsu2018.py
- colour/utilities/__init__.py
- colour/utilities/data_structures.py
- colour/utilities/tests/test_data_structures.py
- docs/colour.recovery.rst
- docs/colour.utilities.rst
As I was improving coverage in *Otsu (2018)* and implemented unit tests, I started to simplify the various interfaces and started to be bothered by the lack of clean separation between the _Data_, _Node_ and _Tree_ classes. To improve the implementation, I added a new `colour.utilities.Node` class that is inherited by `colour.recovery.otsu2018.Node_Otsu2018` class. The colorimetric computations capabilities have all been moved to the `colour.recovery.otsu2018.Data_Otsu2018` class, the name is not ideal since the class is not purely about data but lacking of better, this is, for now, the way.
I shaved a lot of fat and kept only the minimal set of attributes and methods.
> PR: Refactor "Otsu (2018)" classes.

- .github/workflows/continuous-integration.yml
- colour/io/__init__.py
- colour/io/ocio.py
- colour/io/tests/resources/config-aces-reference.ocio.yaml
- colour/io/tests/test_ocio.py
- colour/utilities/__init__.py
- colour/utilities/common.py
- colour/utilities/verbose.py
- docs/colour.io.rst
- docs/colour.utilities.rst
- pyproject.toml
References #654.
The API is as follows:
```python
>>> config = os.path.join(os.path.dirname(__file__), 'tests', 'resources',  'config-aces-reference.ocio.yaml')
>>> a = full([4, 2, 3], 0.18)
>>> process_image_OpenColorIO(a, 'ACES - ACES2065-1', 'ACES - ACEScct', config=config)
array([[[ 0.4135878...,  0.4135878...,  0.4135878...],
[ 0.4135878...,  0.4135878...,  0.4135878...]],
[[ 0.4135878...,  0.4135878...,  0.4135878...],
[ 0.4135878...,  0.4135878...,  0.4135878...]],
[[ 0.4135878...,  0.4135878...,  0.4135878...],
[ 0.4135878...,  0.4135878...,  0.4135878...]],
[[ 0.4135878...,  0.4135878...,  0.4135878...],
[ 0.4135878...,  0.4135878...,  0.4135878...]]], dtype=float32)
>>> process_image_OpenColorIO(a, 'ACES - ACES2065-1', 'Display - sRGB',  'Output - SDR Video - ACES 1.0', …
```
> PR: Implement support for "OpenColorIO" processor.

- colour/colorimetry/blackbody.py
This PR cherry-picks https://github.com/colour-science/colour/pull/926/commits/f6350d99405cc8dabe7cf76150928623b5cc7af4 from @ntessore to bypass the develop merge in #926.
> PR: Use "np.expm1" in "colour.colorimetry.planck_law" definition.

- colour/io/tests/test_tm2714.py
- colour/io/tm2714.py
Fairly straightforward, but: please consider whether it suffices to just compare the complete set of properties or whether the mapping attributes need also be compared.
> PR: Add __eq__, __ne__, and __hash__ methods for "colour.io.tm2714.Header_IESTM2714" class.

- colour/notation/datasets/munsell/real.py
Quick addition in docstring, since I had to research this information myself, about the illuminant of the Munsell dataset renotation.
> PR: Add "Munsell Renotation System" reference illuminant in the data header.

- colour/models/rgb/datasets/ebu_3213_e.py
- colour/models/rgb/datasets/itut_h_273.py
- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/iec_61966_2.py
- colour/models/rgb/transfer_functions/itur_bt_1361.py
- colour/models/rgb/transfer_functions/itut_h_273.py
- colour/models/rgb/transfer_functions/st_428.py
- colour/models/rgb/video.py
This implements what's discussed in #982.
I tried to stick as close to the original ISO standard as possible, but there are a few caveats:
- Some sets of primaries/whitepionts as well as transfer functions were not already present in colour ; I implemented them here based on the ISO standard in this module and added the necessary references.
- The ISO standard is not very clear on the values of alpha, beta and gamma for ITU-R BT.1361, so I chose instead to implement the OETF based on that standard.
- I'm not very certain of how I should implement EOTFs/OETFs when the range is not [0-1] (e.g. BT.1361, which has an extended range). Is there any consensus on that? How is it usually documented?
- I linked the RGB <-> XYZ matrices from the original module in colour even though they are not …
> PR: Add aliases for ITU-T H.273 video color metadata

- .github/workflows/continuous-integration-documentation.yml
- .github/workflows/continuous-integration-quality-unit-tests.yml
- BIBLIOGRAPHY.bib
- colour/__init__.py
- colour/appearance/__init__.py
- colour/appearance/cam16.py
- colour/appearance/ciecam02.py
- colour/appearance/ciecam16.py
- colour/appearance/hellwig2022.py
- colour/appearance/kim2009.py
- colour/appearance/tests/test_cam16.py
- colour/appearance/tests/test_ciecam02.py
- colour/appearance/tests/test_hellwig2022.py
- colour/appearance/zcam.py
- colour/graph/conversion.py
- colour/models/jzazbz.py
- colour/quality/cfi2017.py
- docs/colour.appearance.rst
This PR implements support for *Hellwig, Stolitzka  and Fairchild (2022)* *Helmholtz–Kohlrausch* effect extension for the following Colour Appearance Models (CAM):
- *CIECAM02*
- *CAM16*
- *Hellwig and Fairchild (2022)*
*CIECAM16* was purposely left untouched.
- [N/A ] New transformations have been exported to the relevant namespaces, e.g. `colour`, `colour.models`.
> PR: Implement support for "Hellwig, Stolitzka  and Fairchild (2022)" "Helmholtz–Kohlrausch" effect extension.

- BIBLIOGRAPHY.bib
- colour/__init__.py
- colour/appearance/__init__.py
- colour/appearance/cam16.py
- colour/appearance/ciecam02.py
- colour/appearance/hellwig2022.py
- colour/appearance/tests/test_cam16.py
- colour/appearance/tests/test_ciecam02.py
- colour/quality/cfi2017.py
- docs/colour.appearance.rst
The current implementation for *CIECAM02* and *CAM16* is incorrect as it needs to use the modified chroma correlate which turns out the be the new Hellwig 2022 CAM. See #1047 for more details.
> PR: Revert (partially) "Implement support for "Hellwig, Stolitzka  and Fairchild (2022)" "Helmholtz–Kohlrausch" effect extension."

- colour/continuous/signal.py
This PR implements a performance improvement for `Signal` in `signal.py`. 
The initialization of _function, the private backing attribute for the `function` property, is relatively expensive. This performance issue was discovered when creating an MSDS object from a long list of SpectralDistributions or large ndarrays. The _create_function is invoked frequently when not needed. This PR updates relavent code to always use the function property. the function property has been changed to only invoke _create_function if the _function property has been invalidated (by setting it equal to None). If the function property is never accessed, then the relevant initialization does not take place (lazy initialization)
Under some conditions, this change results in a 90% reduction in Signal …
> PR: Improve initialization time of "Signal", a core component of "Colour".

- colour/colorimetry/spectrum.py
- colour/utilities/array.py
This PR makes small changes to improve the performance of several critical paths that are found throughout the code base. For example, tsplit and tstack are called very often. Additionally, the `shape` getter of `SpectralDistribution` is called very often in code that is manipulating spectral data. In one example calculating color rendering simulations, calling the .shape getter was responsible for around 10% of total execution time, but is now responsible for less than 0.1% 
The particular examples that found these critical paths are not expected to be representative of all performance cases, none the less nearly all applications of colour-science should see some benefit. 
- …
> PR: Performance improvements to `colour.SpectralDistribution.wavelengths` property and various definitions in `colour.utilities.array` module.

- colour/continuous/abstract.py
- colour/continuous/tests/test_abstract.py
- colour/continuous/tests/test_multi_signal.py
- colour/continuous/tests/test_signal.py
This PR implements support for continuous signal iteration while preventing code hanging while iterating by error on a `colour.SpectralDistribution` or `colour.MultiSpectralDistributions` class instances.
```python
import colour
sd = colour.SDS_ILLUMINANTS["A"]
for i in sd:
print(i)
```
```
[ 300.          0.930483]
[ 305.         1.12821]
[ 310.         1.35769]
[ 315.         1.62219]
[ 320.         1.92508]
[ 325.        2.2698]
[ 330.         2.65981]
[ 335.         3.09861]
[ 340.         3.58968]
[ 345.         4.13648]
[ 350.         4.74238]
[ 355.        5.4107]
[ 360.         6.14462]
[ 365.        6.9472]
[ 370.         7.82135]
[ 375.        8.7698]
[ 380.        9.7951]
[ 385.       10.8996]
[ 390.       12.0853]
[ 395.       13.3543]
[ 400.      14.708]
[ 405.      16.148]
[ …
```
> PR: Implement support for continuous function iteration.

- colour/characterisation/datasets/colour_checkers/chromaticity_coordinates.py
Added TE226 V2 color checking values for issue: https://github.com/colour-science/colour/issues/901
- [N/A] Unit tests have been implemented and passed.
- [N/A] Pyright static checking has been run and passed.
> PR: Add TE226 v2 colour checker reference values.

- colour/plotting/temperature.py
- colour/temperature/__init__.py
- colour/temperature/robertson1968.py
- colour/temperature/tests/test_robertson1968.py
- docs/colour.temperature.rst
This PR adds the `colour.mired_to_CCT` and `colour.CCT_to_mired` definitions to support micro reciprocal degree conversion.
> PR: Implement support for "CCT" to "mired" conversion.

- colour/blindness/machado2009.py
- colour/characterisation/aces_it.py
- colour/colorimetry/photometry.py
- colour/colorimetry/spectrum.py
- colour/colorimetry/tests/test_spectrum.py
- colour/colorimetry/transformations.py
- colour/colorimetry/tristimulus_values.py
- colour/plotting/section.py
- colour/quality/cfi2017.py
- colour/quality/cqs.py
- colour/quality/cri.py
- colour/quality/ssi.py
- colour/recovery/jiang2013.py
- colour/recovery/otsu2018.py
This PR as discussed with @tjdcs, adds a new `copy` argument to the `colour.colorimetry.reshape_sd` definition to avoid paying a high copy cost when it is not required.
> PR: Add new `copy` argument to `colour.colorimetry.reshape_sd` definition.

- .github/workflows/continuous-integration-documentation.yml
- .github/workflows/continuous-integration-quality-unit-tests.yml
- colour/characterisation/aces_it.py
- colour/examples/characterisation/examples_colour_checkers.py
- colour/examples/models/examples_models.py
- colour/graph/conversion.py
- colour/models/rgb/common.py
- colour/models/rgb/ictcp.py
- colour/models/rgb/rgb_colourspace.py
- colour/models/rgb/tests/test_rgb_colourspace.py
- colour/plotting/common.py
- colour/plotting/models.py
- colour/plotting/section.py
- colour/plotting/tests/test_section.py
- colour/plotting/volume.py
- colour/recovery/jakob2019.py
- colour/recovery/smits1999.py
- colour/recovery/tests/test_jakob2019.py
- colour/recovery/tests/test_mallett2019.py
- colour/volume/rgb.py
- utilities/generate_plots.py
This PR updates the following definition signatures according to #1127:
- `colour.XYZ_to_RGB`
- `colour.RGB_to_XYZ`
- `colour.matrix_RGB_to_RGB`
- `colour.RGB_to_RGB`
> PR: Update `colour.XYZ_to_RGB` and `colour.RGB_to_XYZ` and related definition signatures.

- BIBLIOGRAPHY.bib
- colour/graph/conversion.py
- colour/notation/__init__.py
- colour/notation/css_color_3.py
- colour/notation/datasets/__init__.py
- colour/notation/datasets/css_color_3.py
- colour/notation/datasets/munsell/__init__.py
- colour/notation/datasets/munsell/all.py
- colour/notation/datasets/munsell/experimental.py
- colour/notation/datasets/munsell/real.py
- colour/notation/munsell.py
- colour/notation/tests/test_css_color_3.py
- colour/utilities/tests/test_array.py
- docs/colour.notation.rst
Yeah, I know... No comments...
> PR: Implement support for "CSS Color 3".

- colour/utilities/__init__.py
- colour/utilities/common.py
- colour/utilities/tests/test_common.py
- colour/utilities/verbose.py
- docs/colour.utilities.rst
- pyproject.toml
This PR implements support for fast integer digest using [xxhash](https://pypi.org/project/xxhash/) with the `colour.utilities.int_digest` definition. If `xxhash` is not available it falls back to the builtin `hash` definition.
The main use case is hashing of the `ndarray` as highlighted in PR #1120.
> PR: Implement support for fast integer digest using "xxhash".

- colour/characterisation/datasets/colour_checkers/chromaticity_coordinates.py
- colour/examples/models/examples_models.py
- colour/graph/tests/test_conversion.py
- colour/models/cie_xyy.py
- colour/models/tests/test_cie_xyy.py
- colour/plotting/diagrams.py
- colour/plotting/models.py
This one has been itching me for a while, it is a very old behaviour that is very strongly opinionated but not recommended by CIE during the computation of chromaticity coordinates: When the tristimulus values are null, we do set the chromaticity coordinates to the passed illuminant ones and the luminance to zero. This is what Bruce Lindbloom is doing. It is quite useful as it means that the achromatic colours are all on the same axis but I reckon that this is a behaviour that should be controlled by the user post-conversion. We do not do that with any other space for that matter.
- [] Pyright static checking has been run and passed.
- [N/A] New transformations have been …
> PR: Remove ability to pass illuminant in "CIE XYZ" to "CIE xyY" related transformations.

- colour/quality/ssi.py
- colour/quality/tests/test_ssi.py
Hey!
While implementing my own version of the 'Spectral Similarity Index' and comparing it to the 'colour-science' module I found some small discrepancies. It seems like there is a small error, probably stemming from an unclear wording in the original white paper by the academy [(link to the project page)](https://www.oscars.org/science-technology/projects/spectral-similarity-index-ssi) 
The [old white paper from 03/2019](https://www.oscars.org/sites/oscars/files/ssi_overview_2019-03-04.pdf) that was used for the original [PR#534](https://github.com/colour-science/colour/pull/534) stated:
> 8) Add zero to each end of weighted relative difference vector to have 32 values, then convolve
with {0.22, 0.56, 0.22} to create smoothed weighted relative difference vector.
The convolution step was …
> Update the 'SSI' calculation to match the revised academy white paper.

- colour/models/rgb/transfer_functions/__init__.py
- colour/models/rgb/transfer_functions/canon.py
- colour/models/rgb/transfer_functions/tests/test_canon.py
This PR implements support for **Canon** v1.2 encodings that define their constants in legal range. Minor numerical differences because of the rounding of the constants are expected.
References #1176.
> PR: Implement support for "Canon" v1.2 encodings.

- colour/colorimetry/generation.py
- colour/colorimetry/tests/test_generation.py
The `colour.colorimetry.sd_gaussian_fwhm` output was not correct as per #1171.
> PR: Fix incorrect `colour.colorimetry.sd_gaussian_fwhm` definition output.

- colour/algebra/common.py
- colour/algebra/extrapolation.py
- colour/algebra/interpolation.py
- colour/appearance/ciecam16.py
- colour/models/rgb/transfer_functions/itur_bt_2100.py
- colour/notation/munsell.py
- colour/utilities/array.py
- colour/utilities/tests/test_array.py
This PR ensures that the `colour.utilities.as_float` definition do not reduce dimensionality. We piggy backed on some of its behaviour but it is inconsistent and caused issues when processing 1-pixel images.
References #1188.
> PR: Ensure that the`colour.utilities.as_float` definition do not reduce dimensionality

- colour/io/ctl.py
- colour/io/tests/resources/Adjust_Exposure_Float.ctl
- colour/io/tests/resources/Adjust_Exposure_Float3.ctl
- colour/io/tests/test_ctl.py
While trying to get set up for `invoke preflight` i couldn't run the CTL examples. Following install instructions from brew did not result in a working ctlrender script. After discussion on ampas/CTL/issues/134 I build CTL render from source and got a working implementation on my MacOS Apple Silicon laptop. 
It checks a few additional conditions. I believe these are backwards compatible with older versions of ctl render but do not know for sure.  
Reference discussion here: https://github.com/ampas/CTL/issues/134
Thank you @michaeldsmith
> Update CTL examples and implementation against latest `ctlrender` built from source.

- colour/hints/__init__.py
- colour/io/luts/__init__.py
- colour/io/luts/tests/test__init__.py
- docs/colour.hints.rst
- utilities/literalise.py
This PR ensures that a LUT can be read or written when the given path has no known extension.
References #1212.
> PR: Ensure that LUT reading and writing can occur when path has no known extension.

- colour/__init__.py
- docs/advanced.rst
This PR injects `vaab/colour` objects into our namespace to address #1221,  #958 and https://github.com/vaab/colour/issues/62.
This is really gross but it will help users so...
```python
from colour import Color, web2rgb
print(Color, web2rgb)
```
```
/Users/kelsolaar/Library/Caches/pypoetry/virtualenvs/colour-science-49B8_mty-py3.11/bin/python /Users/kelsolaar/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/pydevconsole.py --mode=client --host=127.0.0.1 --port=56376 
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/Users/kelsolaar/Documents/Development/colour-science/colour'])
Python 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)]
Type 'copyright', 'credits' or 'license' for more …
```
> PR: Implement support for injecting `vaab/colour` objects  into our namespace.

- README.rst
- colour/adaptation/__init__.py
- colour/adaptation/fairchild2020.py
- colour/adaptation/tests/test_fairchild2020.py
- colour/adaptation/tests/test_vonkries.py
- colour/adaptation/vonkries.py
- docs/colour.adaptation.rst
- docs/index.rst
This PR implements support for *Von Tries (2020)* chromatic adaptation transform.
References #891.
> PR: Implement support for "vK20" chromatic adaptation transform.

- colour/__init__.py
- colour/examples/models/examples_models.py
- colour/graph/conversion.py
- colour/models/__init__.py
- colour/models/cie_lab.py
- colour/models/cie_luv.py
- colour/models/tests/test_cie_lab.py
- colour/models/tests/test_cie_luv.py
- colour/notation/munsell.py
- colour/plotting/models.py
- colour/quality/cqs.py
- colour/volume/pointer_gamut.py
- docs/colour.models.rst
This PR implements support for programmatic polar conversions and adds the following definitions:
- `colour.Lab_to_LCHab` *
- `colour.LCHab_to_Lab` *
- `colour.Luv_to_LCHuv` *
- `colour.LCHuv_to_Luv` *
- `colour.hdr_CIELab_to_hdr_CIELCHab`
- `colour.hdr_CIELCHab_to_hdr_CIELab`
- `colour.Hunter_Lab_to_Hunter_LCHab`
- `colour.Hunter_LCHab_to_Hunter_Lab`
- `colour.Hunter_Rdab_to_Hunter_RdCHab`
- `colour.Hunter_RdCHab_to_Hunter_Rdab`
- `colour.ICaCb_to_IaCH`
- `colour.IaCH_to_ICaCb`
- `colour.ICtCp_to_ItCH`
- `colour.ItCH_to_ICtCp`
- `colour.IgPgTg_to_IgCH`
- `colour.IgCH_to_IgPgTg`
- `colour.IPT_to_ICH`
- `colour.ICH_to_IPT`
- `colour.Izazbz_to_IzCH`
- `colour.IzCH_to_Izazbz`
- `colour.Jzazbz_to_JzCH`
- `colour.JzCH_to_Jzazbz`
- `colour.hdr_IPT_to_hdr_ICH`
- `colour.hdr_ICH_to_hdr_IPT`
- …
> PR: Implement support for programmatic polar conversions.

- colour/algebra/interpolation.py
- colour/colorimetry/generation.py
- colour/colorimetry/lefs.py
`SpragueInterpolator` is the default interpolator for `SpectralDistribution` making it a highly frequented code path. This PR greatly improves the performance of interpolation by using vectorized code and numpy.
Other interpolators could be similarly sped up but they are lower priority.
> PR: Improve performance of SpragueInterpolator

- colour/constants/common.py
Replace np.float_ with np.double for numpy 2.0 compatibility. This allows importing the colour module without error again. ( #1273 )
> PR: Numpy 2 Compatibility: Replace `np.float_` w/ `np.double`.

- colour/models/rgb/transfer_functions/itur_bt_1886.py
This PR ensures that `colour.algebra.spow` is used in *ITU-R BT.1886* colour component transfer functions to avoid NaN generation when negative values are passed.
References #1295
- [N/A] New transformations have been added to the _Automatic Colour Conversion Graph_.
> PR: Use `colour.algebra.spow` in *ITU-R BT.1886* colour component transfer functions

- .github/workflows/continuous-integration-documentation.yml
- .github/workflows/continuous-integration-quality-unit-tests.yml
- .github/workflows/continuous-integration-static-type-checking.yml
- colour/examples/io/examples_ctl.py
- colour/examples/io/examples_fichet2021.py
- docs/requirements.txt
- pyproject.toml
- requirements.txt
This PR implements support for Python 3.13.
- [N/A] New transformations have been added to the _Automatic Colour Conversion Graph_.
> PR: Implement support for Python 3.13.

- colour/difference/__init__.py
- colour/difference/delta_e.py
- colour/difference/tests/test_delta_e.py
- colour/hints/__init__.py
- docs/colour.difference.rst
> PR: Implement support for *HyCH* large color difference

- colour/models/cie_xyy.py
Python Example:
1 - 0.680 - 0.320 = -5.551115123125783e-17;
1 - (0.680 + 0.320) = 0.0
> Change xyY_to_XYZ function to prevent negative floating point error in some cases

- colour/quality/tests/test_cri.py
Currently, the CRI test function only tests a subset of the calculated
data. The attribute `Q_a` and the colorimetry data are not tested,
although the reference data object has reference values.
This patch adds the missing tests.
> PR: CRI: Test All Calculated Data

- colour/adaptation/cie1994.py
- colour/algebra/common.py
- colour/algebra/interpolation.py
- colour/algebra/tests/test_interpolation.py
- colour/appearance/ciecam02.py
- colour/appearance/hke.py
- colour/appearance/rlab.py
- colour/characterisation/aces_it.py
- colour/examples/contrast/examples_contrast.py
- colour/hints/__init__.py
- colour/io/luts/sony_spimtx.py
- colour/models/igpgtg.py
- colour/models/osa_ucs.py
- colour/models/rgb/transfer_functions/linear.py
- colour/quality/ssi.py
- colour/recovery/jakob2019.py
- colour/recovery/meng2015.py
- colour/temperature/cie_d.py
- colour/temperature/hernandez1999.py
- colour/temperature/kang2002.py
- colour/temperature/krystek1985.py
- colour/temperature/mccamy1992.py
- colour/temperature/planck1900.py
- colour/utilities/array.py
- colour/volume/mesh.py
- pyproject.toml
- requirements.txt
This adds [scipy-stubs](https://github.com/scipy/scipy-stubs) as a development dependency. By doing so, 58 new pyright errors popped up. There were 18 that were caused by two bugs and two other issues in `scipy-stubs`, and I've fixed them. See https://github.com/scipy/scipy-stubs/issues/495 for details. 
The other 40 errors turned out to be typing issues in `colour` itself. I have included their fixes in this PR.
~I also noticed that an additional error pops up when the latest `numpy==2.2.4` release is installed (currently pinned at `2.2.0`). I've addressed this in https://github.com/numpy/numpy/pull/28660, and the fix will be included in the upcoming `2.2.5` (and `2.3.0`) NumPy release(s).~ (resolved in [numpy 2.2.5](https://github.com/numpy/numpy/releases/tag/v2.2.5))
This additionally …
> PR: Add `scipy-stubs` as development dependency.

- .github/workflows/continuous-integration-quality-unit-tests.yml
- colour/examples/io/examples_fichet2021.py
- colour/io/fichet2021.py
- colour/io/image.py
- colour/io/tests/test_fichet2021.py
- colour/io/tests/test_image.py
- colour/utilities/__init__.py
- colour/utilities/requirements.py
- docs/colour.utilities.rst
- docs/requirements.txt
- pyproject.toml
- requirements.txt
This PR makes [OpenImageIO](https://openimageio.readthedocs.io) required and [Imageio](https://imageio.readthedocs.io) optional thanks to the new Python wheels.
- [N/A] New transformations have been added to the _Automatic Colour Conversion Graph_.
> PR: Make *OpenImageIO* required and *ImageIO* optional.

- colour/algebra/common.py
- colour/algebra/tests/test_common.py
This PR adds a new "Replace With Epsilon" mode to the `colour.algebra.sdiv` function and related definitions. This mode provides an alternative approach for handling division by zero by replacing zero denominators with the machine epsilon value (`colour.constants.EPSILON`).
Two new modes have been added:
- `"Replace With Epsilon"`: Silently replaces zero denominators with `EPSILON`
- `"Warning Replace With Epsilon"`: Same as above but issues a warning when zeros are detected
This provides a numerically stable alternative to existing zero-division handling strategies.
- [N/A] New transformations have been added to the _Automatic Colour Conversion Graph_. …
> Update `colour.algebra.sdiv` definition signature to support replacing with `colour.constants.EPSILON` constant.

- colour/hints/__init__.py
Since `numpy>=2.1`, the `float64` and `complex128` scalar types differ from `double` and `cdouble` (see https://github.com/numpy/numpy/issues/29151 for details and https://github.com/numpy/numpy/pull/29155 for the fix). The sized types are (almost always) preferred. And usually, that's already done here. But this case what a bit of an exception, so I corrected it.
> PR: Prefer `complex64` and `complex128` over `csingle` and `cdouble`.
